{% set version = "0.4" %}

package:
  name: bias_correction
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/bias-correction/bias_correction-{{ version }}.tar.gz
  sha256: 969c0b77856ffa1dbd9cf5c827b937dd91abe3850b40a2044c994ffc91eeee06

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - xarray
    - pandas
    - statsmodels

test:
  requires:
    - python {{ python_min }}
  imports:
    - bias_correction

about:
  home: https://github.com/pankajkarman/bias_correction
  license: MIT
  license_file: LICENSE
  summary: python library for bias_correction

extra:
  recipe-maintainers:
    - pankajkarman
    - aaronspring
